-------------------------------------------------------------------------------
-- Dice Master (C) 2023 <The League of Lordaeron> - Moon Guard
-------------------------------------------------------------------------------
--

--
-- The roll options list
-- name			Name of the roll option
-- subName		Pattern for subbing text in description tooltips
-- wheelName	Name to display on the Roll Wheel
-- desc			Description of the roll option
-- skill		Skill used as a modifier
--

DiceMaster4.RollList = {
	["Combat Actions"] = {
		{
			name = "Melee Attack",
			subName = "Melee Attack[s]?",
			wheelName = "Melee|nAttack",
			icon = "Interface/Icons/ability_meleedamage",
			iconID = 40,
			desc = "An attempt to strike an enemy with a melee weapon.", 
			skill = "Strength",
		},
		{
			name = "Ranged Attack",
			subName = "Ranged Attack[s]?",
			wheelName = "Ranged|nAttack",
			icon = "Interface/Icons/ability_piercedamage",
			iconID = 41,
			desc = "An attempt to strike an enemy with a ranged weapon.", 
			skill = "Dexterity",
		},
		{
			name = "Spell Attack",
			subName = "Spell Attack[s]?",
			wheelName = "Spell|nAttack",
			icon = 135989,
			iconID = 42,
			desc = "An attempt to cast a harmful spell against an enemy.", 
			skill = "Intelligence",
		},
		{
			name = "Defence",
			subName = "Defen[cs]e[s]?",
			icon = "Interface/Icons/ability_defend",
			iconID = 43,
			desc = "An attempt to defend yourself from enemy damage.",
			skill = "Constitution",
		},
		{
			name = "Spell Defence",
			subName = "Spell Defen[cs]e[s]?",
			icon = "Interface/Icons/spell_arcane_massdispel",
			iconID = 44,
			desc = "An attempt to defend yourself from enemy spell damage.",
			skill = "Intelligence",
		},
	},
	["Skills"] = {
		{
			name = "Acrobatics",
			subName = "Acrobatics",
			wheelName = "Acrob.",
			icon = "Interface/Icons/ability_rogue_quickrecovery",
			iconID = 132301,
			desc = "An attempt to dive, flip, jump, and An attempt to avoid attacks and overcome obstacles.", 
			skill = "Dexterity",
		},
		{
			name = "Arcana",
			subName = "Arcana",
			icon = "Interface/Icons/spell_arcane_focusedpower",
			iconID = 63,
			desc = "An attempt to recall lore about spells and magic items.", 
			skill = "Intelligence",
		},
		{
			name = "Athletics",
			subName = "Athletics",
			wheelName = "Athle.",
			icon = "Interface/Icons/rogue_burstofspeed",
			iconID = 51,
			desc = "An attempt to swim, climb, flee, fly, or outrun someone.", 
			skill = "Strength",
		},
		{
			name = "Bluff",
			subName = "Bluff",
			icon = "Interface/Icons/spell_shadow_charm",
			iconID = 4,
			desc = "An attempt to deceive, trick, or lie to someone.", 
			skill = "Charisma",
		},
		{
			name = "Diplomacy",
			subName = "Diplomacy",
			wheelName = "Diplom.",
			icon = "Interface/Icons/achievement_general_dungeondiplomat",
			iconID = 0,
			desc = "An attempt to persuade or win favour with someone.", 
			skill = "Charisma",
		},
		{
			name = "Disable Device",
			subName = "Disable Device",
			wheelName = "Disable|nDevice",
			icon = "Interface/Icons/ability_hunter_traplauncher",
			iconID = 2,
			desc = "An attempt to disarm a trap or disable a lock.", 
			skill = "Dexterity",
		},
		{
			name = "Disguise",
			subName = "Disguise",
			icon = "Interface/Icons/ability_rogue_disguise",
			iconID = 27,
			desc = "An attempt to change your appearance.", 
			skill = "Charisma",
		},
		{
			name = "Escape",
			subName = "Escape",
			wheelName = "Escape",
			icon = "Interface/Icons/ability_rogue_trip",
			iconID = 25,
			desc = "An attempt to slip bonds and escape from grapples.", 
			skill = "Dexterity",
		},
		{
			name = "Grapple",
			subName = "Grapple[s]?",
			icon = "Interface/Icons/ability_rogue_grapplinghook",
			iconID = 10,
			desc = "An attempt to disarm or disable an enemy, or reverse grapples.", 
			skill = "Strength",
		},
		{
			name = "Healing",
			subName = "Heal[ingsed]*",
			wheelName = "Heal",
			icon = "Interface/Icons/spell_holy_heal",
			iconID = 53,
			desc = "An attempt to mend wounds or restore health to someone.", 
			skill = "Wisdom",
		},
		{
			name = "Insight",
			subName = "Insight",
			wheelName = "Sense|nMotive",
			icon = "Interface/Icons/spell_holy_spiritualguidence",
			iconID = 20,
			desc = "An attempt to discern intent or decipher body language.", 
			skill = "Wisdom",
		},
		{
			name = "Intimidation",
			subName = "Intimidation",
			wheelName = "Intimidate",
			icon = "Interface/Icons/ability_physical_taunt",
			iconID = 54,
			desc = "An attempt to taunt, coerce, or frighten someone.", 
			skill = "Charisma",
		},
		{
			name = "Knowledge",
			subName = "Knowledge",
			icon = "Interface/Icons/ability_mage_studentofthemind",
			iconID = 8,
			desc = "An attempt to determine your education or understanding of a particular topic.", 
			skill = "Intelligence",
		},
		{
			name = "Perception",
			subName = "Perception",
			wheelName = "Percep.",
			icon = "Interface/Icons/ability_eyeoftheowl",
			iconID = 7,
			desc = "An attempt to notice fine details and alert yourself to danger.", 
			skill = "Wisdom",
		},
		{
			name = "Performance",
			subName = "Performance[s]?",
			wheelName = "Perform",
			icon = "Interface/Icons/inv_mask_01",
			iconID = 13,
			desc = "An attempt to impress an audience with your talent and skill.", 
			skill = "Charisma",
		},
		{
			name = "Spellcraft",
			subName = "Spellcraft",
			icon = "Interface/Icons/spell_arcane_studentofmagic",
			iconID = 21,
			desc = "An attempt to cast or use spells and magic items.", 
			skill = "Intelligence",
		},
		{
			name = "Stealth",
			subName = "Stealth",
			wheelName = "Sneak",
			icon = "Interface/Icons/ability_stealth",
			iconID = 55,
			desc = "An attempt to avoid detection and remain unseen.", 
			skill = "Dexterity",
		},
		{
			name = "Survival",
			subName = "Survival",
			wheelName = "Survive",
			icon = "Interface/Icons/ability_hunter_huntervswild",
			iconID = 23,
			desc = "An attempt to survive or navigate in the wilderness.", 
			skill = "Wisdom",
		},
	},
	["Saving Throws"] = {
		{
			name = "Fortitude Save",
			subName = "Fortitude Save[s]?",
			wheelName = "Fort.|nSave",
			icon = "Interface/Icons/spell_holy_wordfortitude",
			iconID = 56,
			desc = "An attempt to resist physical punishment or pain.", 
			skill = "Constitution",
		},
		{
			name = "Reflex Save",
			subName = "Reflex Save[s]?",
			wheelName = "Reflex|nSave",
			icon = "Interface/Icons/ability_rogue_quickrecovery",
			iconID = 58,
			desc = "An attempt to avoid or prevent an unexpected action.", 
			skill = "Dexterity",
		},
		{
			name = "Will Save",
			subName = "Will Save[s]?",
			wheelName = "Will|nSave",
			icon = "Interface/Icons/ability_kaztik_dominatemind",
			iconID = 57,
			desc = "An attempt to resist mental influence.", 
			skill = "Wisdom",
		},
	},
}

DiceMaster4.AttributeList = {
	["Strength"] = {
		icon = "Interface/Icons/spell_nature_strength",
		desc = "A measure of your muscle and physical power.",
	},
	["Dexterity"] = {
		icon = "Interface/Icons/ability_rogue_sprint",
		desc = "A measure of your hand-eye coordination, agility, reflexes, and balance.",
	},
	["Constitution"] = {
		icon = "Interface/Icons/spell_holy_blessingofstamina",
		desc = "A measure of your health and stamina.",
	},
	["Intelligence"] = {
		icon = "Interface/Icons/spell_holy_magicalsentry",
		desc = "A measure of how well you learn and reason.",
	},
	["Wisdom"] = {
		icon = "Interface/Icons/spell_holy_sealofwisdom",
		desc = "A measure of your willpower, common sense, awareness, and intuition.",
	},
	["Charisma"] = {
		icon = "Interface/Icons/spell_brokenheart",
		desc = "A measure of your personality, personal magnetism, ability to lead, and appearance.",
	},
}

DiceMaster4.TermsList = {
	["Effects"] = {
		{
			name = "Advantage",
			subName = "Advantage",
			iconID = 38,
			desc = "Allows a character to roll the same dice twice, and take the greater of the two resulting numbers.",
		},
		{
			name = "Armour Penetration",
			subName = "Arm[ou]*r Penetration",
			iconID = 16,
			desc = "Allows a character's successful attack to bypass the target's Armour this turn.",
		},
		{
			name = "Cleave",
			subName = "Cleave[s]*",
			iconID = 30,
			desc = "Allows a character's successful attack to inflict damage to up to two additional targets.",
		},
		{
			name = "Control",
			subName = "Control[sleding]*",
			iconID = 47,
			desc = "Allows a character to take command of a target and control their actions until the effect ends.",
		},
		{
			name = "Counter",
			subName = "Counter[seding]*",
			iconID = 48,
			desc = "Allows a character to immediately attack the same target after a successful Defence roll.",
		},
		{
			name = "Disadvantage",
			subName = "Disadvantage",
			iconID = 39,
			desc = "Allows a character to roll the same dice twice, and take the lesser of the two resulting numbers.",
		},
		{
			name = "Disarm",
			subName = "Disarm[s]*",
			iconID = 31,
			desc = "Removes a target's weapons for one turn, preventing them from using them.",
		},
		{
			name = "Dispel",
			subName = "Dispel[sleding]*",
			iconID = 61,
			desc = "Removes a buff or debuff from a creature.",
		},
		{
			name = "Double or Nothing",
			subName = "Double or Nothing",
			iconID = 32,
			desc = "An unmodified D40 roll. If the roll succeeds, the character is rewarded with a critical success; however, if the roll fails, the character suffers a critical failure.",
		},
		{
			name = "Empower",
			subName = "Empower[seding]*",
			iconID = 45,
			desc = "Allows a character's successful Melee Attack or Ranged Attack to be considered a Spell Attack.",
		},
		{
			name = "Immunity",
			subName = "Immunity",
			iconID = 46,
			desc = "Prevents a character from suffering any damage from a failure this turn.",
		},
		{
			name = "Intercept",
			subName = "Intercept[edsing]*",
			iconID = 49,
			desc = "Intercepts another character's failure, taking the full amount of damage.",
		},
		{
			name = "Leech",
			subName = "Leech[edsing]*",
			iconID = 62,
			desc = "Causes damage inflicted by a character to also restore an equal amount of their health.",
		},
		{
			name = "Multistrike",
			subName = "Multistrike",
			iconID = 28,
			desc = "Allows a character to attack twice on their turn; however, their second attack only inflicts 1 damage (2 if critically successful).",
		},
		{
			name = "Natural 1",
			subName = "NAT1",
			iconID = 37,
			desc = "A roll of 1 that is achieved before dice modifiers are applied that results in critical failure.",
			altTerm = "NAT1",
		},
		{
			name = "Natural 20",
			subName = "NAT20",
			iconID = 36,
			desc = "A roll of 20 that is achieved before dice modifiers are applied that results in critical success.",
			altTerm = "NAT20",
		},
		{
			name = "Reflect",
			subName = "Reflect[edsing]*",
			iconID = 50,
			desc = "Causes damage intended for a character to reflect back at the attacker.",
		},
		{
			name = "Reload",
			subName = "Reload[edsing]*",
			iconID = 29,
			desc = "Grants the character's active-use trait another use.",
		},
		{
			name = "Revive",
			subName = "Reviv[desing]*",
			iconID = 34,
			desc = "Allows a character with |cFFFFFFFF0|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100 remaining to return to combat with |cFFFFFFFF3|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100.",
		},
		{
			name = "Secret",
			subName = "Secret[s]*",
			iconID = 60,
			desc = "A secret effect that remains hidden until activated by a specific condition.",
		},
		{
			name = "Taunt",
			subName = "Taunt[seding]*",
			iconID = 59,
			desc = "Forces a target to attack the character on its next turn (if permitted).",
		},
	},
	["Conditions"] = {
		{
			name = "Blind",
			altName = "Blind",
			subName = "Blind[seding]*",
			icon = "Interface/Icons/ability_cheapshot",
			iconID = 1,
			desc = "The target is unable to see and automatically fails any ability check that requires sight. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			animation = 77,
		},
		{
			name = "Charm",
			altName = "Charmed",
			subName = "Charm[seding]*",
			icon = "Interface/Icons/spell_shadow_seduction",
			iconID = 3,
			desc = "The target is entranced and unable to attack the charmer. The charmer has Advantage on any ability check to interact socially with the target.",
			effect = 63837,
			animation = 83,
		},
		{
			name = "Deafen",
			altName = "Deaf",
			subName = "Deafen[seding]*",
			icon = "Interface/Icons/inv_misc_ear_human_01",
			iconID = 5,
			desc = "The target is unable to hear and automatically fails any ability check that requires hearing.",
		},
		{
			name = "Fatigue",
			altName = "Fatigued",
			subName = "Fatigu[esding]*",
			icon = "Interface/Icons/spell_shadow_mindsteal",
			iconID = 6,
			desc = "The target cannot run nor charge. The target has Disadvantage on Fortitude and Reflex Saves.",
			animation = 1154,
		},
		{
			name = "Frighten",
			altName = "Frightened",
			subName = "Frighten[seding]*",
			icon = "Interface/Icons/spell_shadow_possession",
			iconID = 9,
			desc = "The target has Disadvantage on ability checks and attack rolls while the source of its fear is within line of sight. The target cannot willingly move closer to the source of its fear.",
			effect = 123888,
			animation = 225,
		},
		{
			name = "Grapple",
			altName = "Grappled",
			subName = "Grappl[edsing]*",
			icon = "Interface/Icons/spell_nature_shamanrage",
			iconID = 10,
			desc = "The target is unable to move for the duration of the Grapple. The condition ends if the grappler is incapacitated.",
			animation = 14,
		},
		{
			name = "Incapacitate",
			altName = "Incapacitated",
			subName = "Incapacitat[esding]*",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 11,
			desc = "The target cannot take actions or reactions.",
			animation = 14,
		},
		{
			name = "Invisible",
			altName = "Invisible",
			subName = "Invisib[ilitye]*",
			icon = "Interface/Icons/spell_nature_invisibilty",
			iconID = 12,
			desc = "The target is impossible to see without the aid of magic or a special sense. Attack rolls against the target have Disadvantage, and the target's attack rolls have Advantage.",
			effect = 118726,
		},
		{
			name = "Paralyse",
			altName = "Paralysed",
			subName = "Paraly[sz]*[esding]*",
			icon = "Interface/Icons/spell_nature_wispsplodegreen",
			iconID = 14,
			desc = "The target cannot take actions or reactions, move, or speak. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			animation = 14,
		},
		{
			name = "Petrify",
			altName = "Petrified",
			subName = "Petrif[iyesding]*",
			icon = "Interface/Icons/ability_golemthunderclap",
			iconID = 15,
			desc = "The target is transformed into solid stone and cannot take actions or reactions, move, or speak. Attack rolls against the target have Advantage. The target is immune to poison and disease, but automatically fails Fortitude and Reflex Saves.",
		},
		{
			name = "Poison",
			altName = "Poisoned",
			subName = "Poison[seding]*",
			icon = "Interface/Icons/spell_nature_nullifydisease",
			iconID = 18,
			desc = "The target has Disadvantage on attack rolls and ability checks.",
			effect = 108139,
			animation = 8,
		},
		{
			name = "Prone",
			altName = "Prone",
			subName = "Prone",
			icon = "Interface/Icons/ability_rogue_feigndeath",
			iconID = 19,
			desc = "The target's only movement option is to crawl, unless it stands up and ends the condition. The target has Disadvantage on attack rolls. Melee Attack rolls against the target have Advantage, but Ranged Attack rolls have Disadvantage.",
			animation = 121,
		},
		{
			name = "Restrain",
			altName = "Restrained",
			subName = "Restrain[seding]*",
			icon = "Interface/Icons/inv_misc_net_01",
			iconID = 22,
			desc = "The target is unable to move and has Disadvantage on Reflex Saves. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			effect = 14468,
			animation = 1316,
		},
		{
			name = "Silence",
			altName = "Silenced",
			subName = "Silenc[esding]*",
			icon = "Interface/Icons/spell_holy_silence",
			iconID = 33,
			desc = "Interrupts a target's spellcast and prevents them from casting spells on their next turn.",
			animation = 8,
		},
		{
			name = "Slow",
			altName = "Slowed",
			subName = "Slow[seding]*",
			icon = "Interface/Icons/spell_nature_slow",
			iconID = 35,
			desc = "Reduces a target's movement speed until the effect ends.",
			animation = 1160,
		},
		{
			name = "Stun",
			altName = "Stunned",
			subName = "Stun[sneding]*",
			icon = "Interface/Icons/spell_frost_stun",
			iconID = 24,
			desc = "The target cannot take actions or reactions, cannot move, and can speak only falteringly. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			effect = 14482,
			animation = 14,
		},
		{
			name = "Unconscious",
			altName = "Unconscious",
			subName = "Unconscious",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 26,
			desc = "The target cannot take actions or reactions, cannot move or speak, and drops whatever it is holding. The target automatically fails Fortitude and Reflex Saves and attack rolls against the target have Advantage.",
			effect = 91304,
			animation = 100,
		},
	},
	["Other"] = {
		{
			name = "Armour",
			subName = "Armo[u]*r",
			desc = "Extends a character's Health beyond the maximum amount by a certain value. Damage taken will usually be deducted from Armour before Health unless otherwise specified.",
			altTerm = "AR",
		},
		{
			name = "Health",
			subName = "Health",
			desc = "A measure of a character's health or an object's integrity. Damage taken decreases Health, and healing restores Health.",
			altTerm = "HP",
		},
	},
}
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DiceMaster4.RollListWoWJdR = {
	["Habilidades"] = {
		{
			name = "Atletismo",
			subName = "Atletismo",
			wheelName = "Athl",
			icon = 132120,
			desc = "La habilidad física que tiene el personaje a la hora de correr, esprintar, empujar….", 
			skill = "Destreza",
		},
		{
			name = "Sigilo",
			subName = "Sigilo",
			wheelName = "Sigilo",
			icon = 132320,
			desc = "La capacidad de caminar y esconderte en las sombras y evitar ser descubierto.", 
			skill = "Destreza",
		},
		{
			name = "Juego de Manos",
			subName = "Juego de Manos",
			wheelName = "Juego de Manos",
			icon = 1360761,
			desc = "La agilidad, destreza y sutileza con la que manejas tus manos para maniplar mecanismos delicados o poder tocar a alguien sin que este se entere.", 
			skill = "Destreza",
		},		
		{
			name = "Subsistencia",
			subName = "Subsistencia",
			wheelName = "Subsistencia",
			icon = "Interface/Icons/ability_ambush",
			desc = "Cuando tu personaje está en situaciones adversas la supervivencia cuenta y cada vez que se enfrenta a ella los instintos primarios le ayudan a sobrevivir.", 
			skill = "Inteligencia",
		},
		{
			name = "Acrobacias",
			subName = "Acrobacias",
			wheelName = "Acrobacias",
			icon = "Interface/Icons/ability_rogue_quickrecovery",
			desc = "La capacidad de tu personaje de realizar acrobacias sin caerse.", 
			skill = "Destreza",
		},
		{
			name = "Buscar",
			subName = "Buscar",
			wheelName = "Buscar",
			icon = 4419344,
			desc = "La habilidad para localizar objetivos de interés utilizando los sentidos del personaje, se puede utilizar también para registrar personajes, jugadores, cadáveres, baúles… etc.", 
			skill = "Percepción",
		},
		{
			name = "Alerta",
			subName = "Alerta",
			wheelName = "Alerta",
			icon = 132130,
			desc = "El personaje puede tener los sentidos agudizados y prever el riesgo de recibir un golpe, o detectar a alguien bajo sigilo.", 
			skill = "Percepción",
		},
		{
			name = "Aprendizaje",
			subName = "Aprendizaje",
			wheelName = "Aprendizaje",
			icon = 236225,
			desc = "La habilidad de un personaje a la hora de recibir nuevas lecciones y de asimilar esas lecciones.", 
			skill = "Inteligencia",
		},
		{
			name = "Interpretación",
			subName = "Interpretación",
			wheelName = "Interpretación",
			icon = "Interface/AddOns/DiceMaster/Icons/Bard_MusicalNotation",
			desc = "Las capacidades interpretativas del personaje de interpretar y saber leer las actuaciones de otros personajes.", 
			skill = "Carisma",
		},
		{
			name = "Subterfugio",
			subName = "Subterfugio",
			wheelName = "Subterfugio",
			icon = 132288,
			desc = "La picardía que tiene el personaje a la hora de mentir y manipular a las personas para el fin que el personaje desea realizar.", 
			skill = "Carisma",
		},
		{
			name = "Trato con animales",
			subName = "Trato con animales",
			wheelName = "Trato con animales",
			icon = 132165,
			desc = "Tu personaje tiene la capacidad de influir en los animales, ya sea por que huelas bien, los trates con respeto o seas amistoso con ellos.", 
			skill = "Carisma",
		},
		{
			name = "Intimidación",
			subName = "Intimidación",
			wheelName = "Intimidación",
			icon = 236310,
			desc = "Cuando un personaje está en una conversación e intenta sacar algo en un negocio e intenta convencer a alguien y ante las negativas tu personaje puede tratar de intimidar a al receptor en cuestión.", 
			skill = "Carisma",
		},
		{
			name = "Diplomacia",
			subName = "Diplomacia",
			wheelName = "Diplomacia",
			icon = 236550,
			desc = "La capacidad de tu personaje a llegar a acuerdos de forma amistosa.", 
			skill = "Percepción",
		},
	},
	["Habilidades mágicas"] = {
		{
			name = "Taumaturgia",
			subName = "Taumaturgia",
			wheelName = "Taumaturgia",
			icon = 135738,
			desc = "Un usuario de magia manifiesta el poder de dominar las energías sobrenaturales de la creación cuando comienza a comprenderlas, cuanto más lo comprenda mejor le saldrá su conjuro y más efectivo será.", 
			skill = "Inteligencia",
		},
		{
			name = "Fe",
			subName = "Fe",
			wheelName = "Fe",
			icon = 135987,
			desc = "Un creyente que abraza una entidad y busca su favor es bendecido por aquello por lo que siente devoción.", 
			skill = "Voluntad",
		},
		{
			name = "Espiritualidad",
			subName = "Espiritualidad",
			wheelName = "Espiritualidad",
			icon = 4631364,
			desc = "La conexión del usuario con los planos espirituales y los seres vinculados a ellas mediante pactos con los propios espíritus.", 
			skill = "Voluntad",
		},
		{
			name = "Naturaleza",
			subName = "Naturaleza",
			wheelName = "Naturaleza",
			icon = 136041,
			desc = "Aquel que estudie a la naturaleza y establezca vínculos con la misma podrá despertar el poder de la vida misma.", 
			skill = "Voluntad",
		},
		{
			name = "Caos",
			subName = "Caos",
			wheelName = "Caos",
			icon = 132851,
			desc = "Aquellos que dominan las artes oscuras alterando los poderes primordiales corrompiéndolos y deformándolos para crear nuevas ramas mágicas se nutres de la corrupción misma.", 
			skill = "Inteligencia",
		},
	},
	["Defensas"] = {
		{
			name = "Parada y Bloqueo",
			subName = "Parada y Bloqueo",
			wheelName = "Parada y Bloqueo",
			icon = 132359,
			desc = "La capacidad de defenderse con armas cuerpo a cuerpo.", 
			skill = "Vigor",
		},
		{
			name = "Esquivar",
			subName = "Esquivar",
			wheelName = "Esquivar",
			icon = 135994,
			desc = "La habilidad más antigua de la existencia, anticiparse a los movimientos del atacante y moverse para evitar el ataque del enemigo da el nombre de esquivar a esta habilidad.", 
			skill = "Destreza",
		},
		{
			name = "Abjuración Mágica",
			subName = "Abjuración Mágica",
			wheelName = "Abjuración Mágica",
			icon = 135733,
			desc = "Protección basada en magia arcana o magia vil que se basa en crear hechizos de protección individual o grupal para evitar heridas o disuadir a los enemigos de atacar.", 
			skill = "Inteligencia",
		},
		{
			name = "Abjuración de deidad",
			subName = "Abjuración de deidad",
			wheelName = "Abjuración de deidad",
			icon = "Interface/AddOns/DiceMaster/Icons/WH_WindsProtection",
			desc = "Protección basada en las deidades de la Luz, Naturaleza o Espirituales. que se basa en crear hechizos de protección individual o grupal para evitar heridas o disuadir a los enemigos de atacar.", 
			skill = "Voluntad",
		},
	},
	["Armas"] = {
		{
			name = "Espadas de una mano",
			subName = "Espadas de una mano",
			wheelName = "Espadas de una mano",
			icon = 3736884,
			desc = "La habilidad de manejar espadas de una mano de un peso ligero que permite al usuario manejar espadas de una mano.", 
			skill = "Destreza",
		},
		{
			name = "Espadas de dos manos",
			subName = "Espadas de dos manos",
			wheelName = "Espadas de dos manos",
			icon = 3736886,
			desc = "La habilidad de manejar de mandobles que resultan pesados para algunos personajes permite al personaje manejar espadas de dos manos.", 
			skill = "Vigor",
		},
		{
			name = "Mazas de una mano",
			subName = "Mazas de una mano",
			wheelName = "Mazas de una mano",
			icon = 3736923,
			desc = "La habilidad de maniobrar con armas pesadas sin filo que dañan con el impacto permite al usuario manejar mazas de una mano con soltura y destreza.", 
			skill = "Destreza",
		},
		{
			name = "Mazas de dos manos",
			subName = "Mazas de dos manos",
			wheelName = "Mazas de dos manos",
			icon = 3736922,
			desc = "Las armas sin filo que causan daño con el impacto pueden ser muy pesadas, tanto que a veces requieren utilizarlas con dos manos para mejorar su maniobrabilidad.", 
			skill = "Vigor",
		},
		{
			name = "Hachas de una mano",
			subName = "Hachas de una mano",
			wheelName = "Hachas de una mano",
			icon = 3736876,
			desc = "Un arma de filo corta y pesada sostenida por una empuñadura corta que permite al usuario combatir a distancias cortas con ella.", 
			skill = "Destreza",
		},
		{
			name = "Hachas de dos manos",
			subName = "Hachas de dos manos",
			wheelName = "Hachas de dos manos",
			icon = "Interface/Icons/inv_axe_2h_newplayer_a_01",
			desc = "Un arma de filo muy pesada sostenida por una empuñadura larga capaz de ser sostenida por ambas manos, cuyo impacto puede llegar a ser devastador.", 
			skill = "Vigor",
		},
		{
			name = "Arcos",
			subName = "Arcos",
			wheelName = "Arcos",
			icon = "Interface/Icons/inv_bow_1h_newplayer_a_01",
			desc = "Armas simples creadas a base de una madera flexible y una cuerda tensada que permite lanzar punzantes flechas a una velocidad vertiginosa y provocar heridas letales en el enemigo.", 
			skill = "Destreza",
		},
		{
			name = "Armas de fuego",
			subName = "Armas de fuego",
			wheelName = "Armas de fuego",
			icon = 645221,
			desc = "Armas creadas por la maravilla de la ingeniería que mediante una bala de metal impulsada por una explosión de pólvora provocan importantes daños a distancias largas.", 
			skill = "Destreza",
		},
		{
			name = "Armas Arrojadizas",
			subName = "Armas Arrojadizas",
			wheelName = "Armas Arrojadizas",
			icon = 132324,
			desc = "Algunas armas de filo son compactas y ligeras, ideales para lanzarlas y ocasionarles daños a los enemigos, la habilidad en armas arrojadizas aumenta la puntería y la destreza en lanzar dichas armas.", 
			skill = "Destreza",
		},
		{
			name = "Ballestas",
			subName = "Ballestas",
			wheelName = "Ballestas",
			icon = "Interface/Icons/inv_crossbow_2h_kultirasquest_b_01",
			desc = "Una modificación del arco con el fin de aumentar la potencia del disparo dio pie a la invención de esta arma.", 
			skill = "Destreza",
		},
		{
			name = "Bastones",
			subName = "Bastones",
			wheelName = "Bastones",
			icon = "Interface/Icons/inv_staff_2h_newplayer_a_01",
			desc = "Los palos largos ligeros y sin filo son considerados bastones, y aquellos que han recibido instrucción para manejar dichas armas pueden causar importantes daños con un golpe de bastón.", 
			skill = "Destreza",
		},
		{
			name = "Varitas",
			subName = "Varitas",
			wheelName = "Varitas",
			icon = 135467,
			desc = "Los focos de magia encantados pueden ser considerados varitas, aquellos que puedan entender los misterios de la magia que encierran dichas varitas pueden utilizarlas para lanzar los conjuros.", 
			skill = "Inteligencia",
		},
		{
			name = "Dagas",
			subName = "Dagas",
			wheelName = "Dagas",
			icon = 948101,
			desc = "Las armas cortas punzantes y que contienen filo, son consideradas dagas y el usuario de las dagas puede adquirir la habilidad de manejar dichas armas para punzar y cortar con precisión.", 
			skill = "Destreza",
		},
		{
			name = "Armas de puño",
			subName = "Armas de puño",
			wheelName = "Armas de puño",
			icon = 950903,
			desc = "Las armas específicas que se colocan como anillos que se combate con ellas dando puñetazos.", 
			skill = "Destreza",
		},
		{
			name = "Armas de Asta",
			subName = "Armas de Asta",
			wheelName = "Armas de Asta",
			icon = 950903,
			desc = "Son unas armas de filo corto adherido a un bastón largo para combatir a distancias medias.", 
			skill = "Destreza",
		},
		{
			name = "Gujas de Guerra",
			subName = "Gujas de Guerra",
			wheelName = "Gujas de Guerra",
			icon = 2200994,
			desc = "Espadas de origen Kaldorei son armas utilizadas regularmente por cazadores de demonios.", 
			skill = "Destreza",
		},
		{
			name = "Escudo",
			subName = "Escudo",
			wheelName = "Escudo",
			icon = 134950,
			desc = "El escudo es el suplemento de una armadura y otorga al portador un punto extra de armadura, y puede utilizarlo para golpear con el escudo y provocar importantes daños internos al adversario.", 
			skill = "Destreza",
		},
		{
			name = "Sin Armas",
			subName = "Sin Armas",
			wheelName = "Sin Armas",
			icon = "Interface/AddOns/DiceMaster/Icons/diablo3_wayofthehundredfists",
			desc = "La habilidad de golpear a tu objetivo con las manos desnudas..", 
			skill = "Destreza",
		},
	},
--	["Defensas"] = {
--		{
--			name = "Fortitude Save",
--			subName = "Fortitude Save[s]?",
--			wheelName = "Fort.|nSave",
--			iconID = 56,
--			desc = "An attempt to resist physical punishment or pain.", 
--			skill = "Vigor",
--		},
--	},
}

DiceMaster4.AttributeListWoWJdR = {
	["Vigor"] = {
		desc = "La fuerza física de un personaje proviene de sus músculos que han sido ejercitados a lo largo de su vida y son empleados para realizar tareas que requieren el empleo de la fuerza bruta.",
		icon = 236314,
		rank = 1,
		maxRank = 5,
		skillPosition = 2,
		showOnMenu = true,
	},
	["Destreza"] = {
		desc = "Define la habilidad de un personaje a la hora de realizar ejercicios manuales, de manipular un objeto, uso de la agilidad y del equilibrio.",
		icon = 132219,
		rank = 1,
		maxRank = 5,
		skillPosition = 3,
		showOnMenu = true,
	},
	["Inteligencia"] = {
		desc = "La inteligencia se mide junto con el conocimiento general que tiene el personaje sobre lo que se le ha sido enseñado en el mundo.",
		icon = 135740,
		rank = 1,
		maxRank = 5,
		skillPosition = 4,
		showOnMenu = true,
	},
	["Voluntad"] = {
		desc = "La capacidad mental de un individuo de superar los retos que pongan a prueba la resistencia psicológica del personaje.",
		icon = 135939,
		rank = 1,
		maxRank = 5,
		skillPosition = 5,
		showOnMenu = true,
	},
	["Percepción"] = {
		desc = "Todos los personajes de Azeroth sienten, oyen, ven… pueden percibir cosas, pueden sentir si algo o alguien le acecha, o buscando pueden percibir lo que buscan.",
		icon = "Interface/AddOns/DiceMaster/Icons/WH_EagleEye",
		rank = 1,
		maxRank = 5,
		skillPosition = 6,
		showOnMenu = true,
	},
	["Carisma"] = {
		desc = "La apariencia del personaje y su capacidad de hablar para influir en la gente con buenas palabras.",
		icon = 458228,
		rank = 1,
		maxRank = 5,
		skillPosition = 7,
		showOnMenu = true,
	},
	["Aguante"] = {
		desc = "Determina el aguante del personaje o por así decir las vidas, los puntos de vida determinan los puntos de impacto que el personaje puede soportar.",
		icon = 648207,
		rank = 1,
		maxRank = 5,
		skillPosition = 8,
		showOnMenu = false,
	},
	["Energía"] = {
		desc = "Determina las reservas de energía del personaje ya sea energía, chi, maná….",
		icon = 132848,
		rank = 1,
		maxRank = 5,
		skillPosition = 9,
		showOnMenu = false,
	},
	["Armadura"] = {
		desc = "Clase de Armadura.",
		icon = 134950,
		rank = 0,
		maxRank = 100,
		skillPosition = 10,
		showOnMenu = false,
	},	
	["Velocidad"] = {
		desc = "La velocidad del personaje implica la prioridad de batalla del personaje y la distancia de movimiento.",
		icon = 132307,
		rank = 0,
		maxRank = 100,
		skillPosition = 11,
		showOnMenu = true,
	},
}

DiceMaster4.TermsListJdR = {
	["Effects"] = {
		{
			name = "Advantage",
			subName = "Advantage",
			iconID = 38,
			desc = "Allows a character to roll the same dice twice, and take the greater of the two resulting numbers.",
		},
		{
			name = "Armour Penetration",
			subName = "Arm[ou]*r Penetration",
			iconID = 16,
			desc = "Allows a character's successful attack to bypass the target's Armour this turn.",
		},
		{
			name = "Cleave",
			subName = "Cleave[s]*",
			iconID = 30,
			desc = "Allows a character's successful attack to inflict damage to up to two additional targets.",
		},
		{
			name = "Control",
			subName = "Control[sleding]*",
			iconID = 47,
			desc = "Allows a character to take command of a target and control their actions until the effect ends.",
		},
		{
			name = "Counter",
			subName = "Counter[seding]*",
			iconID = 48,
			desc = "Allows a character to immediately attack the same target after a successful Defence roll.",
		},
		{
			name = "Disadvantage",
			subName = "Disadvantage",
			iconID = 39,
			desc = "Allows a character to roll the same dice twice, and take the lesser of the two resulting numbers.",
		},
		{
			name = "Disarm",
			subName = "Disarm[s]*",
			iconID = 31,
			desc = "Removes a target's weapons for one turn, preventing them from using them.",
		},
		{
			name = "Dispel",
			subName = "Dispel[sleding]*",
			iconID = 61,
			desc = "Removes a buff or debuff from a creature.",
		},
		{
			name = "Double or Nothing",
			subName = "Double or Nothing",
			iconID = 32,
			desc = "An unmodified D40 roll. If the roll succeeds, the character is rewarded with a critical success; however, if the roll fails, the character suffers a critical failure.",
		},
		{
			name = "Empower",
			subName = "Empower[seding]*",
			iconID = 45,
			desc = "Allows a character's successful Melee Attack or Ranged Attack to be considered a Spell Attack.",
		},
		{
			name = "Immunity",
			subName = "Immunity",
			iconID = 46,
			desc = "Prevents a character from suffering any damage from a failure this turn.",
		},
		{
			name = "Intercept",
			subName = "Intercept[edsing]*",
			iconID = 49,
			desc = "Intercepts another character's failure, taking the full amount of damage.",
		},
		{
			name = "Leech",
			subName = "Leech[edsing]*",
			iconID = 62,
			desc = "Causes damage inflicted by a character to also restore an equal amount of their health.",
		},
		{
			name = "Multistrike",
			subName = "Multistrike",
			iconID = 28,
			desc = "Allows a character to attack twice on their turn; however, their second attack only inflicts 1 damage (2 if critically successful).",
		},
		{
			name = "Natural 1",
			subName = "NAT1",
			iconID = 37,
			desc = "A roll of 1 that is achieved before dice modifiers are applied that results in critical failure.",
			altTerm = "NAT1",
		},
		{
			name = "Natural 20",
			subName = "NAT20",
			iconID = 36,
			desc = "A roll of 20 that is achieved before dice modifiers are applied that results in critical success.",
			altTerm = "NAT20",
		},
		{
			name = "Reflect",
			subName = "Reflect[edsing]*",
			iconID = 50,
			desc = "Causes damage intended for a character to reflect back at the attacker.",
		},
		{
			name = "Reload",
			subName = "Reload[edsing]*",
			iconID = 29,
			desc = "Grants the character's active-use trait another use.",
		},
		{
			name = "Revive",
			subName = "Reviv[desing]*",
			iconID = 34,
			desc = "Allows a character with |cFFFFFFFF0|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100 remaining to return to combat with |cFFFFFFFF3|r|TInterface/AddOns/DiceMaster/Texture/health-heart:12|t|cFFffd100.",
		},
		{
			name = "Secret",
			subName = "Secret[s]*",
			iconID = 60,
			desc = "A secret effect that remains hidden until activated by a specific condition.",
		},
		{
			name = "Taunt",
			subName = "Taunt[seding]*",
			iconID = 59,
			desc = "Forces a target to attack the character on its next turn (if permitted).",
		},
	},
	["Conditions"] = {
		{
			name = "Blind",
			altName = "Blind",
			subName = "Blind[seding]*",
			icon = "Interface/Icons/ability_cheapshot",
			iconID = 1,
			desc = "The target is unable to see and automatically fails any ability check that requires sight. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			animation = 77,
		},
		{
			name = "Charm",
			altName = "Charmed",
			subName = "Charm[seding]*",
			icon = "Interface/Icons/spell_shadow_seduction",
			iconID = 3,
			desc = "The target is entranced and unable to attack the charmer. The charmer has Advantage on any ability check to interact socially with the target.",
			effect = 63837,
			animation = 83,
		},
		{
			name = "Deafen",
			altName = "Deaf",
			subName = "Deafen[seding]*",
			icon = "Interface/Icons/inv_misc_ear_human_01",
			iconID = 5,
			desc = "The target is unable to hear and automatically fails any ability check that requires hearing.",
		},
		{
			name = "Fatigue",
			altName = "Fatigued",
			subName = "Fatigu[esding]*",
			icon = "Interface/Icons/spell_shadow_mindsteal",
			iconID = 6,
			desc = "The target cannot run nor charge. The target has Disadvantage on Fortitude and Reflex Saves.",
			animation = 1154,
		},
		{
			name = "Frighten",
			altName = "Frightened",
			subName = "Frighten[seding]*",
			icon = "Interface/Icons/spell_shadow_possession",
			iconID = 9,
			desc = "The target has Disadvantage on ability checks and attack rolls while the source of its fear is within line of sight. The target cannot willingly move closer to the source of its fear.",
			effect = 123888,
			animation = 225,
		},
		{
			name = "Grapple",
			altName = "Grappled",
			subName = "Grappl[edsing]*",
			icon = "Interface/Icons/spell_nature_shamanrage",
			iconID = 10,
			desc = "The target is unable to move for the duration of the Grapple. The condition ends if the grappler is incapacitated.",
			animation = 14,
		},
		{
			name = "Incapacitate",
			altName = "Incapacitated",
			subName = "Incapacitat[esding]*",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 11,
			desc = "The target cannot take actions or reactions.",
			animation = 14,
		},
		{
			name = "Invisible",
			altName = "Invisible",
			subName = "Invisib[ilitye]*",
			icon = "Interface/Icons/spell_nature_invisibilty",
			iconID = 12,
			desc = "The target is impossible to see without the aid of magic or a special sense. Attack rolls against the target have Disadvantage, and the target's attack rolls have Advantage.",
			effect = 118726,
		},
		{
			name = "Paralyse",
			altName = "Paralysed",
			subName = "Paraly[sz]*[esding]*",
			icon = "Interface/Icons/spell_nature_wispsplodegreen",
			iconID = 14,
			desc = "The target cannot take actions or reactions, move, or speak. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			animation = 14,
		},
		{
			name = "Petrify",
			altName = "Petrified",
			subName = "Petrif[iyesding]*",
			icon = "Interface/Icons/ability_golemthunderclap",
			iconID = 15,
			desc = "The target is transformed into solid stone and cannot take actions or reactions, move, or speak. Attack rolls against the target have Advantage. The target is immune to poison and disease, but automatically fails Fortitude and Reflex Saves.",
		},
		{
			name = "Poison",
			altName = "Poisoned",
			subName = "Poison[seding]*",
			icon = "Interface/Icons/spell_nature_nullifydisease",
			iconID = 18,
			desc = "The target has Disadvantage on attack rolls and ability checks.",
			effect = 108139,
			animation = 8,
		},
		{
			name = "Prone",
			altName = "Prone",
			subName = "Prone",
			icon = "Interface/Icons/ability_rogue_feigndeath",
			iconID = 19,
			desc = "The target's only movement option is to crawl, unless it stands up and ends the condition. The target has Disadvantage on attack rolls. Melee Attack rolls against the target have Advantage, but Ranged Attack rolls have Disadvantage.",
			animation = 121,
		},
		{
			name = "Restrain",
			altName = "Restrained",
			subName = "Restrain[seding]*",
			icon = "Interface/Icons/inv_misc_net_01",
			iconID = 22,
			desc = "The target is unable to move and has Disadvantage on Reflex Saves. Attack rolls against the target have Advantage, and the target's attack rolls have Disadvantage.",
			effect = 14468,
			animation = 1316,
		},
		{
			name = "Silence",
			altName = "Silenced",
			subName = "Silenc[esding]*",
			icon = "Interface/Icons/spell_holy_silence",
			iconID = 33,
			desc = "Interrupts a target's spellcast and prevents them from casting spells on their next turn.",
			animation = 8,
		},
		{
			name = "Slow",
			altName = "Slowed",
			subName = "Slow[seding]*",
			icon = "Interface/Icons/spell_nature_slow",
			iconID = 35,
			desc = "Reduces a target's movement speed until the effect ends.",
			animation = 1160,
		},
		{
			name = "Stun",
			altName = "Stunned",
			subName = "Stun[sneding]*",
			icon = "Interface/Icons/spell_frost_stun",
			iconID = 24,
			desc = "The target cannot take actions or reactions, cannot move, and can speak only falteringly. The target automatically fails Fortitude and Reflex Saves. Attack rolls against the target have Advantage.",
			effect = 14482,
			animation = 14,
		},
		{
			name = "Unconscious",
			altName = "Unconscious",
			subName = "Unconscious",
			icon = "Interface/Icons/spell_nature_sleep",
			iconID = 26,
			desc = "The target cannot take actions or reactions, cannot move or speak, and drops whatever it is holding. The target automatically fails Fortitude and Reflex Saves and attack rolls against the target have Advantage.",
			effect = 91304,
			animation = 100,
		},
	},
	["Other"] = {
		{
			name = "Armour",
			subName = "Armo[u]*r",
			desc = "Extends a character's Health beyond the maximum amount by a certain value. Damage taken will usually be deducted from Armour before Health unless otherwise specified.",
			altTerm = "AR",
		},
		{
			name = "Health",
			subName = "Health",
			desc = "A measure of a character's health or an object's integrity. Damage taken decreases Health, and healing restores Health.",
			altTerm = "HP",
		},
	},
}